name: Flashboard
options:
  {} # Removed bundleIdPrefix to prevent conflicts
targets:
  FlashboardApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: FlashboardApp
    bundleId: com.flash.lanka.v5
    dependencies:
      - target: FlashboardKeyboard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flash.lanka.v5
        CODE_SIGN_ENTITLEMENTS: FlashboardApp/FlashboardApp.entitlements
    info:
      path: FlashboardApp/Info.plist
      properties:
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}

  FlashboardKeyboard:
    type: app-extension
    platform: iOS
    deploymentTarget: "15.0"
    sources: FlashboardKeyboard
    bundleId: com.flash.lanka.v5.keyboard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flash.lanka.v5.keyboard
        CODE_SIGN_ENTITLEMENTS: FlashboardKeyboard/FlashboardKeyboard.entitlements
    info:
      path: FlashboardKeyboard/Info.plist
      properties:
        CFBundleDisplayName: Flashboard
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: en-US
            RequestsOpenAccess: true
          NSExtensionPointIdentifier: com.apple.keyboard-service
          NSExtensionPrincipalClass: "FlashboardKeyboard.KeyboardViewController"
