name: Flashboard
options:
  bundleIdPrefix: com.flash
targets:
  FlashboardApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: FlashboardApp
    bundleId: com.flash.lanka
    dependencies:
      - target: FlashboardKeyboard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flash.lanka
    info:
      path: FlashboardApp/Info.plist
      properties:
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}

  FlashboardKeyboard:
    type: app-extension
    platform: iOS
    deploymentTarget: "15.0"
    sources: FlashboardKeyboard
    bundleId: com.flash.lanka.keyboard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flash.lanka.keyboard
    info:
      path: FlashboardKeyboard/Info.plist
      properties:
        CFBundleDisplayName: Flashboard
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: en-US
            RequestsOpenAccess: true
          NSExtensionPointIdentifier: com.apple.keyboard-service
          NSExtensionPrincipalClass: "KeyboardViewController"
