name: Flashboard
options:
  bundleIdPrefix: com.example
  xcodeVersion: "15.0"
targets:
  FlashboardApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: FlashboardApp
    bundleId: com.example.FlashboardApp
    dependencies:
      - target: FlashboardKeyboard
    info:
      path: FlashboardApp/Info.plist
      properties:
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}

  FlashboardKeyboard:
    type: app-extension
    platform: iOS
    deploymentTarget: "15.0"
    sources: FlashboardKeyboard
    bundleId: com.example.FlashboardApp.FlashboardKeyboard
    info:
      path: FlashboardKeyboard/Info.plist
      properties:
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: en-US
            RequestsOpenAccess: true
          NSExtensionPointIdentifier: com.apple.keyboard-service
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).KeyboardViewController"
